<template>
    <v-container>
        <v-layout>
            <v-flex xs12>
                <v-card color="rgb(0,0,0,0)">
                    <v-card-title class="text-center">
                        <h1 class="text-center"> Ethereum Guide </h1>
                    </v-card-title>
                        <v-img
                            src='https://i.imgur.com/H66ebKd.png'
                            aspect-ratio="2"
                        >
                        </v-img>
                        <v-card-actions>
                            <v-layout row justify-start>
                            <v-flex xs2>
                                <v-btn flat>
                                    <v-icon class="blue--text">fab fa-twitter</v-icon>  
                                </v-btn>
                            </v-flex>
                            <v-flex xs2>
                                <v-btn flat>
                                    <v-icon class="blue--text">fab fa-facebook-square</v-icon>
                                </v-btn>
                            </v-flex>
                             <v-flex xs2>
                                <v-btn flat>
                                    <v-icon class="blue--text">fab fa-linkedin</v-icon>
                                </v-btn>
                             </v-flex>
                             <v-flex xs2>
                                <v-btn flat>
                                    <v-icon class="blue--text">fab fa-telegram-plane</v-icon>
                                </v-btn>
                             </v-flex>
                             <v-flex>
                                <v-btn flat>
                                    <v-icon class="green--text">fab fa-whatsapp</v-icon>
                                </v-btn>
                             </v-flex>
                          </v-layout>   
                        </v-card-actions>
                        <v-card-text>
                            <h2>What is Ethereum</h2>
                            <a class="mt-2" href="https://en.wikipedia.org/wiki/Ethereum" target="_blank">Source</a>
                            <v-layout column>
                                <p class="mt-3">
                                   <a href="https://en.wikipedia.org/wiki/Ethereum" target="_blank"> 
                                        Ethereum (ETH) 
                                   </a> is an open source, public, blockchain-based distributed computing 
                                    platform and operating system featuring smart contract (scripting) 
                                    functionality. It supports a modified version of Nakamoto consensus via 
                                    transaction-based state transitions.
                                </p>
                                <p>
                                  <strong>Ether</strong> is a token whose blockchain is generated by the Ethereum platform. 
                                  Ether can be transferred between accounts and used to compensate participant 
                                  mining nodes for computations performed.[3] Ethereum provides a decentralized <a href="https://en.wikipedia.org/wiki/Virtual_machine" target="_blank">
                                  virtual machine</a>, the Ethereum Virtual Machine (EVM), which can execute scripts using an international 
                                  network of public nodes.[4] The virtual machine's <a href="https://en.wikipedia.org/wiki/Instruction_set_architecture" target="_blank">
                                  instruction set</a>, in contrast to others like Bitcoin Script, is thought to be <a href="https://en.wikipedia.org/wiki/Turing_completeness" target="_blank">
                                  Turing-complete</a>. "Gas", an internal transaction pricing mechanism, 
                                  is used to mitigate spam and allocate resources on the network.[4]
                                </p>
                                <p>
                                    Ethereum was proposed in late 2013 by Vitalik Buterin, a cryptocurrency researcher and programmer. Development was funded by an 
                                    online crowdsale that took place between July and August 2014. The system then went live on 30 July 2015, with 72 million 
                                    coins "premined". This accounts for about 68 percent of the total circulating supply in 2019.
                                </p>
                                <p>
                                    In 2016, as a result of the exploitation of a flaw in The DAO project's smart contract software, and subsequent theft of $50 
                                    million worth of ether, Ethereum was split into two separate blockchains – the new separate version became Ethereum (ETH) 
                                    with the theft reversed, and the original continued as Ethereum Classic (ETC).
                                </p>
                                <h3>Etymology</h3>
                                <p class="mt-2">Vitalik Buterin picked the name Ethereum after browsing Wikipedia articles about elements and science fiction, when he found 
                                    the name, noting, "I immediately realized that I liked it better than all of the other alternatives that I had seen; I suppose 
                                    it was the fact that sounded nice and it had the word 
                                    '<a href="https://en.wikipedia.org/wiki/Luminiferous_aether" target="_blank">ether</a>', referring to the hypothetical invisible medium that permeates 
                                    the universe and allows light to travel."
                                </p>
                                <h3>History</h3>
                                <p class="mt-2">
                                    Ethereum was initially described in a white paper by 
                                    <a href="https://en.wikipedia.org/wiki/Vitalik_Buterin" target="_blank">Vitalik Buterin</a>, 
                                    a programmer involved with 
                                    <a href="https://en.wikipedia.org/wiki/Bitcoin_Magazine" target="_blank">Bitcoin Magazine</a>, 
                                    in late 2013 with a goal of building decentralized applications. Buterin had argued that Bitcoin needed a 
                                    <a href="https://en.wikipedia.org/wiki/Scripting_language" target="_blank">scripting language </a>
                                    for application development. Failing to gain agreement, he proposed development of a new platform 
                                    with a more general scripting language.
                                </p>
                                <p>
                                    Ethereum was announced at the North American Bitcoin Conference in Miami, in January, 2014. 
                                    During the same time as the conference, a group of people rented a house in Miami: 
                                    <a href="https://en.wikipedia.org/wiki/Gavin_Wood" target="_blank">Gavin Wood</a>, 
                                    Charles Hoskinson, and Anthony Di Iorio, a Torontonian who financed the project. Di Iorio 
                                    invited friend 
                                    <a href="https://en.wikipedia.org/wiki/Joseph_Lubin_(entrepreneur)" target="_blank">Joseph Lubin</a>, 
                                    who invited reporter Morgen Peck, to bear witness. 
                                    Six months later the founders met again in a house in Zug Switzerland, where Buterin 
                                    told the founders that the project would proceed as a non-profit. Hoskinson left the 
                                    project at that time.
                                </p>
                                <p>
                                    Ethereum was officially with an unusually long list of founders. Anthony Di Iorio wrote 
                                    "Ethereum was founded by Vitalik Buterin, Myself, Charles Hoskinson, Mihai Alisie, & Amir 
                                    Chetrit (the initial 5) in December 2013. Joseph Lubin, Gavin Wood, & Jeffrey Wilke were 
                                    added in early 2014 as founders." Formal development of the Ethereum software project began 
                                    in early 2014 through a Swiss company, Ethereum Switzerland GmbH (EthSuisse). The basic idea 
                                    of putting executable smart contracts in the blockchain needed to be specified before the 
                                    software could be implemented; this work was done by Gavin Wood, then chief technology officer, 
                                    in the Ethereum Yellow Paper that specified the Ethereum Virtual Machine. Subsequently, 
                                    a Swiss non-profit foundation, the Ethereum Foundation (Stiftung Ethereum), was created as well. 
                                    Development was funded by an online public crowdsale during July–August 2014, with the participants 
                                    buying the Ethereum value token (ether) with another digital currency, bitcoin.
                                </p>
                                <p>
                                    Ethereum was officially with an unusually long list of founders. Anthony Di Iorio wrote 
                                    "Ethereum was founded by Vitalik Buterin, Myself, Charles Hoskinson, Mihai Alisie, & Amir 
                                    Chetrit (the initial 5) in December 2013. Joseph Lubin, Gavin Wood, & Jeffrey Wilke were 
                                    added in early 2014 as founders." Formal development of the Ethereum software project 
                                    began in early 2014 through a Swiss company, Ethereum Switzerland GmbH (EthSuisse).
                                    The basic idea of putting executable smart contracts in the blockchain needed to be specified 
                                    before the software could be implemented; this work was done by Gavin Wood, then chief technology 
                                    officer, in the Ethereum Yellow Paper that specified the Ethereum Virtual Machine. Subsequently, 
                                    a Swiss non-profit foundation, the Ethereum Foundation (Stiftung Ethereum), was created as well. 
                                    Development was funded by an online public crowdsale during July–August 2014, with the participants 
                                    buying the Ethereum value token (ether) with another digital currency, bitcoin.
                                </p>
                                <p>
                                    While there was early praise for the technical innovations of Ethereum, questions 
                                    were also raised about its security and scalability.
                                </p>
                                <h3>Enterprise Ethereum Alliance (EEA)</h3>
                                <p class="mt-2">
                                    In March 2017, various blockchain start-ups, research groups, and Fortune 500 companies 
                                    announced the creation of the Enterprise Ethereum Alliance (EEA) with 30 founding members.[
                                    16] By May, the nonprofit organization had 116 enterprise members—including 
                                    <a href="https://en.wikipedia.org/wiki/ConsenSys" target="_blank">ConsenSys</a>, 
                                    <a href="https://en.wikipedia.org/wiki/CME_Group" target="_blank">CME Group</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Cornell_University#Research" target="_blank">Cornell University's research group</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Toyota_Group" target="_blank">Toyota Research Institute</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Samsung_SDS" target="_blank">Samsung SDS</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Microsoft" target="_blank">Microsoft</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Intel" target="_blank">Intel</a>, 
                                    <a href="https://en.wikipedia.org/wiki/J._P._Morgan" target="_blank">J. P. Morgan</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Cooley_LLP" target="_blank">Cooley LLP</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Merck_Group" target="_blank">Merck KGaA</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Depository_Trust_%26_Clearing_Corporation" target="_blank">DTCC</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Deloitte" target="_blank">Deloitte</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Accenture" target="_blank">Accenture</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Banco_Santander" target="_blank">Banco Santander</a>, 
                                    <a href="https://en.wikipedia.org/wiki/The_Bank_of_New_York_Mellon" target="_blank">BNY Mellon</a>, 
                                    <a href="https://en.wikipedia.org/wiki/ING_Group" target="_blank">ING</a>, 
                                    and 
                                    <a href="https://en.wikipedia.org/wiki/National_Bank_of_Canada" target="_blank">National Bank of Canada</a>. 
                                    By July 2017, there were over 150 members in the 
                                    alliance, including recent additions 
                                    <a href="https://en.wikipedia.org/wiki/Mastercard" target="_blank">MasterCard</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Cisco_Systems" target="_blank">Cisco Systems</a>, 
                                    <a href="https://en.wikipedia.org/wiki/Sberbank_of_Russia" target="_blank">Sberbank</a> and 
                                    <a href="https://en.wikipedia.org/wiki/Scotiabank" target="_blank">Scotiabank</a>.
                                </p>
                                <h3>Milestones</h3>
                                <p class="mt-2">
                                    Several codenamed prototypes of the Ethereum platform were developed by the Foundation, 
                                    as part of their Proof-of-Concept series, prior to the official launch of the Frontier network. 
                                    "Olympic" was the last of these prototypes, and public beta pre-release.
                                </p>
                                <p>
                                    The Olympic network provided users with a 
                                    <a href="https://en.wikipedia.org/wiki/Bug_bounty_program" target="_blank">bug bounty</a>
                                     of 25,000 ether for stress testing the 
                                    limits of the Ethereum blockchain. "Frontier" marked the tentative experimental release of the 
                                    Ethereum platform in July 2015.
                                </p>
                                <p>
                                    Since the initial launch, Ethereum has undergone several planned protocol upgrades, which 
                                    are important changes affecting the underlying functionality and/or 
                                    <a href="https://en.wikipedia.org/wiki/Incentive_compatibility" target="_blank">incentive structures</a> 
                                    of the platform
                                </p>
                                <p>
                                    Protocol upgrades are accomplished by means of a soft fork of the open source code base.
                                </p>
                                <p>
                                    "Homestead" was the first to be considered stable. It included improvements to transaction processing, 
                                    gas pricing, and security; and the soft fork occurred on 31 July 2015.
                                </p>
                                <p>
                                    The "Metropolis Part 1: Byzantium" soft fork took effect on 16 October 2017, and 
                                    included changes to reduce the complexity of the EVM and provide more flexibility for smart 
                                    contract developers. Byzantium also added supports for zk-SNARKs (from 
                                    <a href="https://en.wikipedia.org/wiki/Zcash" target="_blank">Zcash</a>), with the 
                                    first zk-SNARK transaction occurring on testnet on September 19, 2017.
                                </p>
                                <p>
                                    The "Metropolis Part 2: Constantinople" hard fork, and the simultaneous "St. Petersburg" 
                                    network upgrade, occurred at block number 7,280,000 on February 28, 2019.
                                </p>
                                <h3>The DAO event</h3>
                                <p class="mt-2">
                                    In 2016 a 
                                    <a href="https://en.wikipedia.org/wiki/Decentralized_autonomous_organization" target="_blank">decentralized autonomous organization</a>
                                     called The DAO, a set of 
                                     <a href="https://en.wikipedia.org/wiki/Smart_contract" target="_blank">smart contracts</a> 
                                    developed on the platform, raised a record US$150 million in a crowdsale to fund the project.
                                    The DAO was exploited in June when US$50 million in ether were taken by an unknown hacker.
                                    The event sparked a debate in the crypto-community about whether Ethereum should perform a 
                                    contentious "hard fork" to reappropriate the affected funds.As a result of the dispute, 
                                    the network split in two. Ethereum (the subject of this article) continued on the forked blockchain, 
                                    while 
                                    <a href="https://en.wikipedia.org/wiki/Ethereum_Classic" target="_blank">Ethereum Classic</a>
                                     continued on the original blockchain. The hard fork created a rivalry 
                                    between the two networks.
                                </p>
                                <p>
                                    After the hard fork related to The DAO, Ethereum subsequently forked twice in the fourth 
                                    quarter of 2016 to deal with other attacks. By the end of November 2016, Ethereum had 
                                    increased its 
                                    <a href="https://en.wikipedia.org/wiki/Denial-of-service_attack" target="_blank">DDoS protection</a>, 
                                    de-bloated the blockchain, and thwarted further spam attacks by hackers.
                                </p>
                                <h3>Characteristics</h3>
                                <p class="mt-2">
                                    As with other cryptocurrencies, the validity of each ether is provided by a 
                                    <a href="https://en.wikipedia.org/wiki/Blockchain" target="_blank">blockchain</a>, which is a 
                                    continuously growing list of records, called blocks, which are linked and secured using 
                                    <a href="https://en.wikipedia.org/wiki/Cryptography" target="_blank">cryptography</a>.
                                    By design, the blockchain is inherently resistant to modification of the data. It is an open, distributed 
                                    ledger that records transactions between two parties efficiently and in a verifiable and permanent way.
                                    Unlike Bitcoin, Ethereum operates using accounts and balances in a manner called state transitions. This does 
                                    not rely upon unspent transaction outputs (UTXOs). State denotes the current balances of all accounts and extra data. 
                                    State is not stored on the blockchain, it is stored in a separate 
                                    <a href="https://en.wikipedia.org/wiki/Merkle_tree" target="_blank">Merkle Patricia tree</a>. A 
                                    <a href="https://en.wikipedia.org/wiki/Cryptocurrency_wallet" target="_blank">cryptocurrency wallet</a> 
                                    stores the 
                                    <a href="https://en.wikipedia.org/wiki/Public-key_cryptography" target="_blank">public and private "keys"</a> or "addresses" which can be used to receive or spend ether. These can be 
                                    generated through BIP 39 style mnemonics for a BIP 32 "HD Wallet". In Ethereum, this is unnecessary as it does 
                                    not operate in a UTXO scheme. With the private key, it is possible to write in the blockchain, effectively 
                                    making an ether transaction.
                                </p>
                                <p>
                                    To send ether to an account, you need the 
                                    <a href="https://en.wikipedia.org/wiki/SHA-3" target="_blank">Keccak-256 hash</a> of the public 
                                    key of that account. Ether accounts are pseudonymous in that they are not linked to individual persons, 
                                    but rather to one or more specific addresses.
                                </p>
                                <h3>Ether</h3>
                                <p class="mt-2">
                                    Ether is a fundamental token for operation of Ethereum, which thereby provides a public 
                                    <a href="https://en.wikipedia.org/wiki/Distributed_ledger" target="_blank">distributed ledger</a>
                                     for transactions. It is used to pay for gas, a unit of computation used in transactions 
                                    and other state transitions. Mistakenly, this currency is also referred to as Ethereum.
                                </p>
                                <p>
                                   It is listed under the ticker symbol ETH and traded on cryptocurrency exchanges, and the Greek 
                                   uppercase Xi character (Ξ) is generally used for its currency symbol. It is also used to pay for 
                                   transaction fees and computational services on the Ethereum network.
                                </p>
                                <h3>Addresses</h3>
                                <p class="mt-2">
                                    Ethereum addresses are composed of the prefix "0x", a common identifier for 
                                    <a href="https://en.wikipedia.org/wiki/Hexadecimal" target="_blank">hexadecimal</a>, 
                                    concatenated with the rightmost 20 bytes of the Keccak-256 hash 
                                    (<a href="https://en.wikipedia.org/wiki/Endianness" target="_blank">big endian</a>) of the 
                                    <a href="https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm" target="_blank">ECDSA</a> 
                                    public key (the curve used is the so called secp256k1, the same as Bitcoin). In hexadecimal, 
                                    2 digits represents a byte, meaning addresses contain 40 hexadecimal digits. An example of an 
                                    Ethereum address is 0xb794F5eA0ba39494cE839613fffBA74279579268. Contract addresses are in the 
                                    same format, however they are determined by sender and creation transaction nonce. User accounts 
                                    are indistinguishable from contract accounts given only an address for each and no blockchain data. 
                                    Any valid Keccak-256 hash put into the described format is valid, even if it does not correspond 
                                    to an account with a private key or a contract. This is unlike Bitcoin, which uses 
                                    <a href="https://en.wikipedia.org/wiki/Base58base58check" target="_blank">base58check</a>
                                    to ensure that addresses are properly typed.
                                </p>
                                <h3>Comparison to bitcoin</h3>
                                <p class="mt-3">
                                    Ethereum is different from Bitcoin (the cryptocurrency with the largest market 
                                    capitalization as of June 2018) in several aspects:
                                </p>
                                <ul>
                                    <li>
                                        Its block time is 14 to 15 seconds, compared with 10 minutes for bitcoin.
                                    </li>
                                    <li>
                                        Mining of ether generates new coins at a usually consistent rate, 
                                        occasionally changing during hard forks, while for bitcoin the rate 
                                        halves every 4 years.
                                    </li>
                                    <li>
                                        For proof-of-work, it uses the Ethash algorithm which reduces the advantage 
                                        of specialized ASICs in mining.
                                    </li>
                                    <li>
                                        Transaction fees differ by computational complexity, bandwidth use and 
                                        storage needs (in a system known as gas), while bitcoin transactions compete 
                                        by means of transaction size, in bytes.
                                    </li>
                                    <li>
                                        Ethereum gas units each have a price that can be specified in a transaction. 
                                        This is typically measured in Gwei. Bitcoin transactions usually have fees 
                                        specified in satoshis per byte.
                                    </li>
                                    <li>
                                        Ethereum uses an account system where values in Wei are debited from accounts 
                                        and credited to another, as opposed to Bitcoin's UTXO system, which is more 
                                        analogous to spending cash and receiving change in return.
                                    </li>
                                </ul>
                                <h3 class="mt-3">Supply</h3>
                                <p class="mt-2">
                                    The total supply of ether was around Ξ106.7 million as of July 5, 2019. In 2017, 
                                    mining generated 9.2 million new ether, corresponding to a 10% increase in its total 
                                    supply. Casper FFG and CBC are expected to reduce the inflation rate to between 0.5% to 2%.
                                    There is no currently implemented hard cap on the total supply of ETH.
                                </p>
                                <h3 class="mt-3">Smart contracts</h3>
                                <p class="mt-3">
                                    Ethereum's 
                                    <a href="https://en.wikipedia.org/wiki/Smart_contract" target="_blank">smart contracts</a>
                                    are based on different computer languages, which developers use 
                                    to program their own functionalities. Smart contracts are high-level programming abstractions 
                                    that are compiled down to EVM bytecode and deployed to the Ethereum blockchain for execution. 
                                    They can be written in Solidity (a language library with similarities to C and JavaScript), 
                                    Serpent (similar to Python, but deprecated), LLL (a low-level Lisp-like language), and Mutan 
                                    (Go-based, but deprecated). There is also a research-oriented language under development called 
                                    Vyper (a strongly-typed Python-derived decidable language).
                                </p>
                                <p>
                                    Smart contracts can be public, which opens up the possibility to prove functionality, e.g. 
                                    self-contained 
                                    <a href="https://en.wikipedia.org/wiki/Provably_fair" target="_blank">provably fair casinos</a>
                                </p>
                                <p>
                                    One issue related to using smart contracts on a public blockchain is that bugs, including 
                                    security holes, are visible to all but cannot be fixed quickly. One example of this is 
                                    the 17 June 2016 attack on The DAO, which could not be quickly stopped or reversed.
                                </p>
                                <p>
                                    There is ongoing research on how to use formal verification to express and prove non-trivial 
                                    properties. A Microsoft Research report noted that writing solid smart contracts can be 
                                    extremely difficult in practice, using The DAO hack to illustrate this problem. 
                                    The report discussed tools that Microsoft had developed for verifying contracts, 
                                    and noted that a large-scale analysis of published contracts is likely to uncover 
                                    widespread vulnerabilities. The report also stated that it is possible to verify the 
                                    equivalence of a Solidity program and the EVM code.
                                </p>
                                <h3 class="mt-3">Applications</h3>
                                <p class="mt-2">
                                    Ethereum apps are written in one of seven different 
                                    <a href="https://en.wikipedia.org/wiki/Turing_completeness" target="_blank">Turing-complete languages</a>. 
                                    Developers use the language to create and publish applications which they know will 
                                    run inside Ethereum. It's a cumbersome system, but that's not deterring developers 
                                    from writing Ethereum programs.
                                </p>
                                <p>
                                    Many uses have been proposed for Ethereum platform, including ones that are impossible or 
                                    unfeasible.Use case proposals have included finance, the internet-of-things, farm-to-table 
                                    produce, electricity sourcing and pricing, and sports betting. Ethereum is (as of 2017) 
                                    the leading blockchain platform for initial coin offering projects, with over 50% market share.
                                    As of January 2018, there are more than 300 live DApps, with hundreds more under development.
                                </p>
                                <h3 class="mt-3">Criticisms</h3>
                                <p class="mt-2">
                                    Izabella Kaminska, the editor of FT Alphaville, has pointed out that criminals are using 
                                    Ethereum to run Ponzi schemes and other forms of investment fraud.The article was based 
                                    on a paper from the University of Cagliari, which placed the number of Ethereum smart contracts 
                                    which facilitate Ponzi schemes at nearly 10% of 1384 smart contracts examined. However, 
                                    it also estimated that only 0.05% of the transactions on the network were related to such contracts.
                                </p>
                            </v-layout>
                        </v-card-text>
                </v-card>
            </v-flex>
        </v-layout>
    </v-container>
</template>


<script>
export default {
    

}
</script>

<style scoped>

</style>